name: databases

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./pg_init_ha.sh:/docker-entrypoint-initdb.d/pg_init_ha.sh
      - ./pg_init_n8n.sh:/docker-entrypoint-initdb.d/pg_init_n8n.sh
    networks:
      - traefik-proxy
    env_file:
      - /home/sathindu/HomeLab/infisical-secrets/.infisical.stacks.databases.postgres.env
    environment:
      - TZ=America/New_York
      - PGTZ=America/New_York
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

volumes:
  postgres-data:
    name: databases-postgres-data

networks:
  traefik-proxy:
    external: true
