name: tools

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=/homelab
      - PROXY_DOMAIN=vsc.pi.lan
      - PWA_APPNAME=HomeLab
    volumes:
      - /home/sathindu/HomeLab/volume-mounts/tools-code-server/config:/config
      - /home/sathindu/HomeLab:/homelab
      - /home/sathindu/.ssh:/config/.ssh:ro   # SSH for Git
    networks:
      - traefik-proxy
    env_file:
      - /home/sathindu/HomeLab/infisical-secrets/.infisical.stacks.tools.code-server.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`vsc.pi.lan`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls=true"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"

networks:
  traefik-proxy:
    external: true