name: tools

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=/homelab
      - PROXY_DOMAIN=vsc.pi.lan
      - PWA_APPNAME=HomeLab
    volumes:
      - /home/sathindu/HomeLab/volume-mounts/tools-code-server/config:/config
      - /home/sathindu/HomeLab:/homelab
      - /home/sathindu/.ssh:/config/.ssh:ro   # SSH for Git
    networks:
      - traefik-proxy
    env_file:
      - /home/sathindu/HomeLab/infisical-secrets/.infisical.stacks.tools.code-server.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`vsc.pi.lan`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls=true"
      - "traefik.http.routers.code-server.middlewares=code-server-headers@file"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=home.pi.lan
    volumes:
      - /home/sathindu/HomeLab/volume-mounts/tools-homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.pi.lan`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    volumes:
      - tools-n8n-data:/home/node/.n8n
    networks:
      - traefik-proxy
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - N8N_HOST=n8n.pi.lan
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_TASK_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_SECURE_COOKIE=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n_user
    env_file:
      - /home/sathindu/HomeLab/infisical-secrets/.infisical.stacks.tools.n8n.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.pi.lan`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  
  n8n-task-runner:
    image: n8nio/runners:latest
    container_name: n8n-task-runner
    restart: unless-stopped
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
    env_file:
      - /home/sathindu/HomeLab/infisical-secrets/.infisical.stacks.tools.n8n-runners.env
    networks:
      - traefik-proxy
    depends_on:
      - n8n


volumes:
  tools-n8n-data:
    name: tools-n8n-data


networks:
  traefik-proxy:
    external: true